### PR TITLE
Filled some entity interfaces.

### PR DESCRIPTION
**Pull request by szymonkrygier**
I will fill more interfaces soon / Niedlugo uzupelnie reszte interfaces

### CODE REVIEW

**Comment by GotoFinal** [comment]
Oh, great, but I will leave this as PR for now, as it will break all builds, just push more changes here when you will have time, and I will merge that later. (and implement if that will be needed)

Thanks for contributing.
Also if this isn't a problem, please use spaces instead of tab.

**Comment by szymonkrygier** [comment]
Sure, no problem.

I've just changed tabs to spaces. See the latest commits.

**Comment by GotoFinal** [comment]
I wanted ask on forum, but seems that it is broken as hell...
You will only add methods to interfaces or you will also implement them later?

**Comment by szymonkrygier** [comment]
I added implementation for those abstract methods but them are empty, just because I don't want to play with bytes today (I'm really good Java programmer, but I'm really green with bytes here).

Edit:

Yeah, the forum's messager seems to be broken (And some other things too).

**Comment by szymonkrygier** [comment]
Sorry for some mistakes, I'm really tired now and I came directly from C++, I don't need to re-include things like here in Java, or add modifier to each method.

But don't worry, I will warm-up really fast. :D

**Comment by GotoFinal** [comment]
What do you use to write code? Most of good IDE do everything for you.
I recommend Intellij IDEA (community edition)

**Comment by GotoFinal** [comment]
like it is just 3 clicks to implement all methods with empty body and default return values.
And it will point all errors like that, or even warn you on commit that code contains errors.

It isn't like cpp where most of errors you see on compile time :D Java is perfect to use with IDE.

**Comment by szymonkrygier** [comment]
I'm using Eclipse.

Probably I need to change like you said.

**Comment by GotoFinal** [comment]
Eclipse o.O
I don't even know how you imported diorite project without any problems, eclipse have huge problems with importing nested modules with maven.

**Comment by szymonkrygier** [comment]
Better don't ask.. There were a lot of problems..

Edit:

And still there are some problems. :D

**Comment by szymonkrygier** [comment]
Will you fill those overrided method?

I can handle that but not today.

**Comment by GotoFinal** [comment]
just leave them for now, we don't need to merge today, and don't care about travis checks.

And install intellij, you will feel difference ;) And importing will be just selecting pom.xml and confirm button.

**Comment by szymonkrygier** [comment]
Ok. :) 

I will contact you on the forum as soon as somebody will fix messages. :)

**Comment by szymonkrygier** [comment]
Check out the forum.

**Comment by GotoFinal** [comment]
closed on request.

**Pull request closed without merging**
