### PR TITLE
Fix some typos / grammar errors

### PR DESCRIPTION
**Pull request by GrumpyBear57**

### CODE REVIEW

**Comment by GotoFinal** [comment]
Weird, for some reason travis failed to build it, but you didn't change anything related to tests. I will check that later, maybe some test is invalid.

**Comment by GrumpyBear57** [comment]
From what I can tell, it's something with your last commit, as that also failed with the same error in Travis. Could be wrong though. 

EDIT: Here I am correcting other's grammar when I apparently can't use it myself. Fixed now :P

**Comment by GotoFinal** [comment]
Ohhh, I see, this is dev branch, I was looking at master one. So, do you want to add anything more or I can merge it now?

**Comment by GrumpyBear57** [comment]
I've skimmed the commits you've put into dev, and from what I can see, it's all good. Mergable!

**Comment by GotoFinal** [comment]
And thanks for contributing ;)

**Comment by GrumpyBear57** [comment]
~You reverted it in 037db3d btw :P~

Never mind, did the dumb

**Pull request merged**
